### ISSUE TITLE
undefined local variable or method `struct_fields'

### ISSUE THREAD

**Issue by mukeshbhati** [carbonfive/active_column#1]
Hi i followed the following docs to make it work
https://github.com/carbonfive/active_column/blob/master/docs/Migrate.md

but when i used the command
rake ks:create

it gaved me following error

rake aborted!
undefined local variable or method `struct_fields' for #Cassandra::Keyspace:0xb6b9c830

(See full trace by running task with --trace)
i am totally clueless what to do can anybody help me out

**Comment by mwynholds** [comment]
You are using the Cassandra 0.6 support in the Cassandra gem, and you must use the 0.7 support.  Use this line in your Gemfile to require Cassandra:

gem 'cassandra', '>= 0.9', :require => 'cassandra/0.7'

I updated the README.md to reflect this.

**Comment by mukeshbhati** [comment]
Thanks , it worked for creating database but when i am migrating it  again giving me error

rake ks:migrate
rake aborted!
nil

**Comment by mwynholds** [comment]
Run this:
rake --trace ks:migrate

and let me know what you get.

**Comment by mukeshbhati** [comment]
HI ..

this issue raised once again i have updated my rails version from 3.0.6.rc1 to 3.0.7 and when i created the keyspace it worked but i runed rake ks:migrate it gaved me this error 

rake aborted!
nil
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/transport/socket.rb:109:in `read'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/transport/base_transport.rb:52:in`read_all'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/transport/framed_transport.rb:78:in `read_frame'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/transport/framed_transport.rb:49:in`read'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/transport/base_transport.rb:52:in `read_all'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/protocol/binary_protocol.rb:186:in`read_i32'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/protocol/binary_protocol.rb:111:in `read_message_begin'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/client.rb:45:in`receive_message'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.1/lib/../vendor/0.7/gen-rb/cassandra.rb:112:in `recv_multiget_slice'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.1/lib/../vendor/0.7/gen-rb/cassandra.rb:104:in`multiget_slice'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:116:in `send'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:116:in`handled_proxy'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:58:in `multiget_slice'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.1/lib/cassandra/protocol.rb:83:in`_multiget'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:599:in `multi_get'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:572:in`get'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:116:in `get_all_versions'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:240:in`migrated'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:156:in `current_version'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:173:in`migrate'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/thrift-0.6.0/lib/thrift/struct.rb:50:in `detect'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:173:in`each'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:173:in `detect'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:173:in`migrate'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:95:in `up'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/migration.rb:77:in`migrate'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/active_column-0.1.1/lib/active_column/tasks/ks.rb:47
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/home/vishnu_swarnkar/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/bin/rake:31
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/bin/rake:19:in`load'
/home/vishnu_swarnkar/.rvm/gems/ruby-1.8.7-p334/bin/rake:19

what should i do ???

**Comment by mwynholds** [comment]
I think maybe you don't have Cassandra running.  Is that the case?

**Comment by mbhati** [comment]
no i was running cassandra , but thrift_client was giving me problem when i was using thrift client "6.0.2" i am facing this problem and if m using thrift client "6.0.0" its working like charm...

**Comment by mwynholds** [comment]
I think you mean thrift_client 0.6.2 vs. 0.6.0.  this might be the issue:
https://github.com/fauna/cassandra/issues/84

looks like there are some dependency issues with thrift and thrift_client gems, and with cassandra gem.  take a look and see if some version hackery in your Gemfile solves things.

**Comment by mwynholds** [comment]
i'm not sure if that helped or not, but hopefully it did.  i am going to close this issue for now.
