### ISSUE TITLE
Keyspace/Column family already exists

### ISSUE THREAD

**Issue by FewKinG** [carbonfive/active_column#16]
This may relate to issue #8.

I have developped an application with a bunch of migrations for it. I now tried to start with a completely empty database. However, running the migrations fails miserably. After creating the keyspace I tried to run the migrations. 

Sometimes it threw an error claiming the column family schema_migrations already existed (which it did then, but not before I ran the migrations). Other times, it skipped that error but then claimed the first column family it tried to create already existed (same here: It didn't exist before, but after I tried to run the migrations). It seems like it attempts to run the same migration twice (don't know if that's what's actually happening though).

It may be worth noting that I encountered some strange behaviour previously when rolling back migrations. Sometimes two migrations had been reverted at once (not just one as I expected).

I already tried (multiple times):
- Dropping the respective column family and retry running the migrations
- Deleting/Recreating the ks/schema.json file
- Dropping the whole keyspace and retry running the migrations
- Dropping ALL data from cassandra and starting with a completly empty database.

I'm using cassandra 1.0.6, the twitter/cassandra gem (latest version, 0.15.0) and the latest version of your active_column gem.

Has anybody a clue what's going wrong here?
Thanks in advance

**Comment by FewKinG** [comment]
Okay, I dug deeper and have some interesting findings. First of all: Your gem is perfectly okay, I checked that both, the active_column gem and the cassandra gem only issued the create commands once.
At this point, it seems that the thrift_client gem somehow issues commands multiple times, see
https://github.com/twitter/thrift_client/issues/38

**Comment by mwynholds** [comment]
interesting.  thanks for investigating.  i know we have thrift set up to
retry... but i assumed that was only on failures.  it will be interesting
to see what comes of your bug report.

..mike..
