### ISSUE TITLE
Completely remove any dependence on Rails code

### ISSUE THREAD

**Issue by kevinrood** [carbonfive/active_column#4]
It would be great if active_column could be used in non-rails projects without using active_support.

**Comment by mwynholds** [comment]
How are you using active_column?  Are you using the database migration support, and/or the Cassandra persistence support?  I haven't really publicized the latter much.

**Comment by kevinrood** [comment]
We're looking at using the migration support.  We might possibly use the persistence support, but so far we've just been using the Cassandra gem persistence.

**Comment by mwynholds** [comment]
There is a Rails generator that's part of the migration support, but definitely if you don't use that it would make sense to not have any dependencies on Rails (or Active Support).  I need to go through and remember all the places we depend on Active Support.  And I'll see if I can get rid of it.  It's a good idea, and one that I considered originally, but landed on the side of leaving it in there (for no great reason).

**Comment by kevinrood** [comment]
Yeah, it's understandable having left it in if your primary use for it was with Rails apps.  It might still be useful to allow more than one environment some how (development, test, etc.).

**Comment by krieghan** [comment]
Is ActiveColumn known to only work on Rails 3, or should it work on Rails 2 as well?

**Comment by kevinrood** [comment]
I'm not sure.  However, the only thing that active_column taps into from Rails should be the Rails generators now.

**Comment by mwynholds** [comment]
Correct.  Although I haven't done a release of this new code yet, master
does not rely on Rails at all, except for the generator (which is just not
loaded if you require active_column in a non-rails app).

So, it should work just fine with Rails 2.

Please let me know if you run in to trouble.

..mike..

**Comment by krieghan** [comment]
Loading the 0.1.1 gem, the Rails 2 application that I'm using loads migration_generator, which requires 'rails/generators'.  As far as I can tell, this is a Rails 3 artifact, and requiring it in Rails 2 results in a "no such file to load".  The Master branch seems to load the migration_generator only if you are using a Rails project.  Unfortunately, if you are using a Rails 2 project it will still load the migration_generator, resulting in the same load error.

I'm not sure how useful it is to you to ensure backward compatibility to Rails 2.  If this is not something that you want to do, I certainly understand, and am certainly more than happy to just vendor the gem for my particular project and make the changes required to make it work with Rails 2.

**Comment by mwynholds** [comment]
i will make it work with Rails 2.  i'll try to do it today or tomorrow...
please hold...

.m.

**Comment by mwynholds** [comment]
I just released active_column 0.2 to rubygems.  The gem itself no longer requires Rails to run, and the generator (which does require Rails) now should work with Rails 2 and Rails 3.

**Comment by kevinrood** [comment]
Sounds excellent - thanks Mike
