### ISSUE TITLE
Where are the migrations stored in Cassandra?  Which keyspace?

### ISSUE THREAD

**Issue by kevinrood** [carbonfive/active_column#5]
I've been getting an error when trying to run ks:migrate.  I think it's related to how the schema_migration records are stored.  How should the migrations work overall?  What's stored where?  Are the migrations using the new schema change features of Cassandra?

**Comment by kevinrood** [comment]
After looking through the code base for quite a bit, I have some general ideas for you about some things.  Do you want to chat some time?  Skype?  Google Talk?  Please let me know.

**Comment by mwynholds** [comment]
Migrations are stored in a column family called "schema_migrations" in your keyspace.  This mimics AR.  Within that column family, there is one row with key "all".  Column names are migration versions, and column values are migration names.
