### ISSUE TITLE
posts already exists in keyspace myapp_development

### ISSUE THREAD

**Issue by tawkoo** [carbonfive/active_column#8]
If I run the migration first time it thinks column family already exists but it does not. I even tried dropping and recreating the keyspace. It creates the column family though but with wrong comparator type.

Here is the output:

rake ks:migrate
==  PostColumnFamily: migrating ===============================================
rake aborted!
posts already exists in keyspace myapp_development

Tasks: TOP => ks:migrate
(See full trace by running task with --trace)

Here is the migration files:

class PostColumnFamily < ActiveColumn::Migration

  def self.up
    create_column_family :posts do |cf|
      cf.comment = 'Posts column family'
      cf.comparator_type = :string
    end
  end
  def self.down
    drop_column_family :posts
  end

This is what it creates:

```
ColumnFamily: posts
"Posts column family"
  Key Validation Class: org.apache.cassandra.db.marshal.BytesType
  Default column value validator: org.apache.cassandra.db.marshal.BytesType
  Columns sorted by: org.apache.cassandra.db.marshal.BytesType
```

end

**Comment by mwynholds** [comment]
There seem to be two issues:
1. post already exists
   I can't reproduce this error.  I added your migration to my test app and it runs fine.  Can you give me any more info?
2. uses wrong comparator class
   Actually, :string is an alias for BytesType, so it's using the right one.  You can use :utf8 for UTF8Type.  I don't have an alias for AsciiType.  What do you think the right type is for :string?

**Comment by tawkoo** [comment]
1) My cassandra.yml looks like this:
test:
  servers: "127.0.0.1:9160"
  keyspace: "myapp_test"
  thrift:
    timeout: 3
    retries: 2

development:
  servers: "127.0.0.1:9160"
  keyspace: "myapp_development"
  thrift:
    timeout: 3
    retries: 2

2) I think you are right about this.

**Comment by mwynholds** [comment]
Same as the other issue... can I clone your repo and try to see this error happen?

**Comment by mwynholds** [comment]
I haven't heard from you in a while. I'm going to close this, but please re-open it (or another issue) if you want to continue discussing it.
